name: Run Unit and E2E tests

on:
  pull_request:
    branches:
      - main

jobs:
  run-unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm run test:unit

  run-e2e-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Start the development server
        run: npm run dev &
        env:
          NEXT_PUBLIC_GRAPHQL: ${{ secrets.NEXT_PUBLIC_GRAPHQL }}

      - name: Wait for the server to be ready
        run: npx wait-on http://localhost:3000

      - name: Run E2E Tests
        run: npm run test:e2e

      # saves cypress screenshots and videos as artifacts
      - name: Upload test:e2e artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: e2e-artifacts
          path: |
            cypress/videos/**/*
            cypress/screenshots/**/*
